CREATE TABLE IF NOT EXISTS EMPLOYEE(
        ID INT  NOT NULL PRIMARY KEY,
        FIRST_NAME VARCHAR(255),
        LAST_NAME VARCHAR(255),
        SALARY DOUBLE,
        );

        INSERT INTO EMPLOYEE VALUES (1, 'John', 'Doe', 10000.10);
        INSERT INTO EMPLOYEE VALUES (2, 'Kevin', 'Smith', 20000.20);
        INSERT INTO EMPLOYEE VALUES (3, 'Kim', 'Smith', 30000.30);
        INSERT INTO EMPLOYEE VALUES (4, 'Stephen', 'Torvalds', 40000.40);
        INSERT INTO EMPLOYEE VALUES (5, 'Christian', 'Reynolds', 50000.50);